variable "hostname" {}
variable "ami" {}
variable "instance_type" {}
variable "instance_count" {}
variable "subnet_id" {}
variable "key_name" {}
variable "zone_id" {}
variable "rev_zone_id" {}
variable "sg_ids" {}
variable "cloud_init" {}
variable "internal_domain" {}
/* provider */
variable "region"               {}
variable "access_key"           {}
variable "secret_key"           {}